import { AUTOMATED_EMAIL_TRIGGERS } from '@/lib/automatedEmailTriggers';

/** Plantillas por defecto si la tabla aún no existe en Supabase. */
export const DEFAULT_AUTOMATED_EMAIL_TEMPLATES = [
  {
    slug: 'welcome_registration',
    nombre: 'Bienvenida al registrarse',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.USER_REGISTERED,
    trigger_reason:
      'Se envía cuando un alumno crea su cuenta en la plataforma (registro público).',
    asunto: '¡Bienvenido/a a Dralo English!',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      '¡Gracias por unirte a Dralo English! Ya formas parte de una comunidad que prepara exámenes Cambridge con práctica real, simulacros y feedback inteligente.',
      '',
      'Tu acceso está listo con el email {{email}}. Entra cuando quieras para practicar reading, writing, listening, speaking y use of English por niveles A2–C2.',
      '',
      '{{login_url}}',
      '',
      'Si tienes cualquier duda, responde a este correo o escríbenos desde la sección Contacto.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'support_ticket_ack',
    nombre: 'Confirmación de ticket de soporte',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.SUPPORT_TICKET_CREATED,
    trigger_reason:
      'Se envía al alumno cuando envía un ticket desde Contacto o «Report error».',
    asunto: 'Hemos recibido tu consulta — Dralo English',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      'Gracias por escribirnos. Hemos recibido tu mensaje y nuestro equipo de soporte ya lo tiene en cola.',
      '',
      'Asunto: {{ticket_subject}}',
      '',
      'Te responderemos lo antes posible, normalmente en un plazo máximo de 48 horas laborables.',
      '',
      'Si quieres añadir más detalles, puedes responder directamente a este correo.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'admin_user_welcome',
    nombre: 'Cuenta creada por administrador',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.ADMIN_USER_CREATED,
    trigger_reason:
      'Se envía cuando un administrador o profesor crea una cuenta con contraseña temporal.',
    asunto: 'Tu cuenta en Dralo English está lista',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      'Un administrador ha creado tu cuenta en Dralo English. Aquí tienes tus datos de acceso:',
      '',
      'Email: {{email}}',
      'Contraseña temporal: {{temporary_password}}',
      '',
      'Por seguridad, te recomendamos cambiar la contraseña en tu perfil nada más iniciar sesión.',
      '',
      '{{login_url}}',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'support_staff_reply',
    nombre: 'Respuesta de soporte al usuario',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.SUPPORT_REPLY_SENT,
    trigger_reason:
      'Se envía al usuario cuando el equipo de soporte responde a su ticket desde el panel.',
    asunto: 'Re: [Soporte] {{ticket_subject}}',
    cuerpo: [
      'Hola,',
      '',
      '{{message}}',
      '',
      '—',
      '{{agent_name}} · Equipo Dralo',
      '{{support_email}}',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'friend_invite',
    nombre: 'Invitar a un amigo',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.FRIEND_INVITED,
    trigger_reason:
      'Se envía cuando un usuario invita a un amigo desde la sección «Invite friends» del perfil.',
    asunto: '{{sender_name}} te invita a practicar en Dralo',
    cuerpo: [
      'Hola,',
      '',
      '{{sender_name}} quiere que practiques inglés juntos en Dralo — la plataforma para preparar exámenes Cambridge (A2–C2) con ejercicios, simulacros de examen y herramientas de IA.',
      '',
      '{{invite_message}}',
      '',
      '{{app_url}}',
      '',
      'Empieza con Exam practice, explora Dralo AI para writing y speaking, y sigue tu progreso desde tu perfil.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
];

export function getDefaultTemplatesByTrigger(triggerEvent) {
  return DEFAULT_AUTOMATED_EMAIL_TEMPLATES.filter((t) => t.trigger_event === triggerEvent);
}
