import { AUTOMATED_EMAIL_TRIGGERS } from '@/lib/automatedEmailTriggers';

/** Plantillas por defecto si la tabla aún no existe en Supabase. */
export const DEFAULT_AUTOMATED_EMAIL_TEMPLATES = [
  {
    slug: 'welcome_registration',
    nombre: 'Bienvenida al registrarse',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.USER_REGISTERED,
    trigger_reason:
      'Se envía cuando un alumno crea su cuenta en la plataforma (registro público).',
    asunto: '¡Bienvenido/a a Dralo English!',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      '¡Gracias por unirte a Dralo English! Ya formas parte de una comunidad que prepara exámenes Cambridge con práctica real, simulacros y feedback inteligente.',
      '',
      'Tu cuenta se ha creado con el email {{email}}. Confirma tu correo desde el mensaje «Confirma tu email» que te acabamos de enviar y podrás practicar reading, writing, listening, speaking y use of English por niveles A2–C2.',
      '',
      '{{login_url}}',
      '',
      'Si tienes cualquier duda, responde a este correo o escríbenos desde la sección Contacto.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'email_confirmation',
    nombre: 'Confirma tu email',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.USER_EMAIL_CONFIRMATION,
    trigger_reason:
      'Se envía al registrarse. Sin confirmar el email no se puede iniciar sesión.',
    asunto: 'Confirma tu email para activar tu cuenta — Dralo English',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      'Falta un paso para activar tu cuenta: confirma que {{email}} es tu dirección de correo.',
      '',
      '{{action_url}}',
      '',
      'Hasta que pulses el botón no podrás iniciar sesión. El enlace solo puede usarse una vez y, al abrirlo, entrarás directamente en tu cuenta.',
      '',
      'Si no te has registrado en Dralo English, puedes ignorar este correo.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'password_reset',
    nombre: 'Recuperar contraseña',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.PASSWORD_RESET_REQUESTED,
    trigger_reason:
      'Se envía cuando alguien pide un enlace de recuperación desde «¿Has olvidado tu contraseña?».',
    asunto: 'Restablece tu contraseña — Dralo English',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      'Hemos recibido una petición para restablecer la contraseña de la cuenta {{email}}.',
      '',
      '{{action_url}}',
      '',
      'El enlace caduca en 1 hora y solo puede usarse una vez. Si caduca, pide uno nuevo desde la página de acceso.',
      '',
      'Si no has pedido este cambio, ignora este correo: tu contraseña actual seguirá funcionando.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'support_ticket_ack',
    nombre: 'Confirmación de ticket de soporte',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.SUPPORT_TICKET_CREATED,
    trigger_reason:
      'Se envía al alumno cuando envía un ticket desde Contacto o «Report error».',
    asunto: 'Hemos recibido tu consulta — Dralo English',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      'Gracias por escribirnos. Hemos recibido tu mensaje y nuestro equipo de soporte ya lo tiene en cola.',
      '',
      'Asunto: {{ticket_subject}}',
      '',
      'Te responderemos lo antes posible, normalmente en un plazo máximo de 48 horas laborables.',
      '',
      'Si quieres añadir más detalles, puedes responder directamente a este correo.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'admin_user_welcome',
    nombre: 'Cuenta creada por administrador',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.ADMIN_USER_CREATED,
    trigger_reason:
      'Se envía cuando un administrador o profesor crea una cuenta con contraseña temporal.',
    asunto: 'Tu cuenta en Dralo English está lista',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      'Un administrador ha creado tu cuenta en Dralo English. Aquí tienes tus datos de acceso:',
      '',
      'Email: {{email}}',
      'Contraseña temporal: {{temporary_password}}',
      '',
      'Por seguridad, te recomendamos cambiar la contraseña en tu perfil nada más iniciar sesión.',
      '',
      '{{login_url}}',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'support_staff_reply',
    nombre: 'Respuesta de soporte al usuario',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.SUPPORT_REPLY_SENT,
    trigger_reason:
      'Se envía al usuario cuando el equipo de soporte responde a su ticket desde el panel.',
    asunto: 'Re: [Soporte] {{ticket_subject}}',
    cuerpo: [
      'Hola,',
      '',
      '{{message}}',
      '',
      '—',
      '{{agent_name}} · Equipo Dralo',
      '{{support_email}}',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'friend_invite',
    nombre: 'Invitar a un amigo',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.FRIEND_INVITED,
    trigger_reason:
      'Se envía cuando un usuario invita a un amigo desde la sección «Invite friends» del perfil.',
    asunto: '{{sender_name}} te invita a practicar en Dralo',
    cuerpo: [
      'Hola,',
      '',
      '{{sender_name}} quiere que practiques inglés juntos en Dralo — la plataforma para preparar exámenes Cambridge (A2–C2) con ejercicios, simulacros de examen y herramientas de IA.',
      '',
      '{{invite_message}}',
      '',
      '{{invite_url}}',
      '',
      'Empieza con Exam practice, explora Dralo AI para writing y speaking, y sigue tu progreso desde tu perfil.',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'staff_task_assigned',
    nombre: 'Asignación de tarea (staff)',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.STAFF_TASK_ASSIGNED,
    trigger_reason:
      'Se envía a la persona asignada cuando se crea una tarea en el panel de tareas del equipo.',
    asunto: 'Nueva tarea asignada: {{task_titulo}}',
    cuerpo: [
      'Hola{{nombre}},',
      '',
      '{{creator_name}} te ha asignado una nueva tarea en el panel de tareas:',
      '',
      'Título: {{task_titulo}}',
      'Prioridad: {{task_prioridad}}',
      '{{task_fase_line}}',
      '{{task_subfase_line}}',
      '{{task_fecha_line}}',
      '{{task_descripcion_line}}',
      '',
      '{{tasks_url}}',
      '',
      '— Equipo Dralo English',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
  {
    slug: 'founding_member_plus',
    nombre: 'Plan Plus — 50 primeras inscripciones',
    trigger_event: AUTOMATED_EMAIL_TRIGGERS.FOUNDING_MEMBER_PLUS_GRANTED,
    trigger_reason:
      'Se envía a las inscripciones 2–50 de la campaña de lanzamiento con Plan Plus gratuito e indefinido.',
    asunto: '¡Plan Plus gratuito e indefinido para ti! — Dralo',
    cuerpo: [
      'Buenas tardes{{nombre}},',
      '',
      'Tenemos una buena noticia para ti 🎉',
      '',
      'Por haber sido una de las 50 primeras personas en registrarse en Dralo, queremos agradecerte la confianza que has depositado en nosotros regalándote el Plan Plus de forma gratuita e indefinida.',
      '',
      'A partir de ahora podrás disfrutar de todas las ventajas incluidas en el Plan Plus sin ningún coste y sin fecha de caducidad.',
      '',
      'Dralo acaba de empezar y todavía tenemos muchísimo por mejorar, añadir y construir. Por eso, para nosotros tiene un valor especial que hayas confiado en el proyecto desde sus primeros pasos.',
      '',
      'Esperamos que Dralo te ayude a preparar tu examen, mejorar tu inglés y, sobre todo, a conseguir ese aprobado que estás buscando. 🚀',
      '',
      'Y esto es solo el principio: durante los próximos meses iremos incorporando nuevos ejercicios, funcionalidades, contenido y mejoras.',
      '',
      'Gracias por formar parte de los primeros usuarios de Dralo. 💙',
      '',
      '¡Nos vemos dentro!',
      '',
      '{{login_url}}',
      '',
      '— Equipo Dralo',
    ].join('\n'),
    activo: true,
    delay_minutos: 0,
    es_sistema: true,
  },
];

export function getDefaultTemplatesByTrigger(triggerEvent) {
  return DEFAULT_AUTOMATED_EMAIL_TEMPLATES.filter((t) => t.trigger_event === triggerEvent);
}
