// Auto-generated by scripts/write-static-export-layouts.mjs — no editar a mano

export function generateStaticParams() {
  return ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'].map((part) => ({ part }));
}

export default function StaticExportPartLayout({ children }) {
  return children;
}
