// Auto-generated by scripts/write-static-export-layouts.mjs — no editar a mano

export function generateStaticParams() {
  return ['1', '2'].map((part) => ({ part }));
}

export default function StaticExportPartLayout({ children }) {
  return children;
}
