// Auto-generated by scripts/write-static-export-layouts.mjs — no editar a mano

export function generateStaticParams() {
  return ['a2', 'b1', 'b2', 'c1', 'c2'].map((cefr) => ({ cefr }));
}

export default function StaticExportCefrLayout({ children }) {
  return children;
}
